# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

def test_reddit(driver) :
  driver.set_window_size(1600, 1200)
  driver.get("https://www.reddit.com/")
  
  driver.implicitly_wait(1)
  title = driver.title
  print(title)
  
  button = driver.find_elements(by=By.ID, value="focus-Popular")
  if not button:
    print("window is too small")
  else:
    button[0].click()
    time.sleep(5)
  driver.quit()

def create_chrome_driver():
  chrome_options = webdriver.ChromeOptions()
  return webdriver.Chrome(options=chrome_options)

